version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "staging"
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "staging"
    labels:
      - "dependencies"
    groups:
      npm-production:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      npm-development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directories:
      - "/apps/rest-api"
      - "/apps/streamwizard-bot"
      - "/apps/ws-server"
      - "/apps/web-streamwizard"
      - "/apps/web-overlay"
    schedule:
      interval: "weekly"
    target-branch: "staging"
    labels:
      - "dependencies"
    groups:
      docker-base-images:
        patterns:
          - "*"
